[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "file-scanner"
version = "0.1.0"
description = "Multi-threaded folder scanner with pluggable processors."
authors = [
    { name = "Sagume", email = "ex@example.com" }
]
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["."]
